export const baseVariant = {
  id: "base",
  title: "Base: Chiral Correspondence",
  description: "Complete the correspondence between two opposite-handed 3D structures by locating the missing voxel.",
  status: "ready",
  examples: ["example1", "example2"],
  tests: ["test"],
  cases: {
    example1: {
      voxels: [
        { pos: [1, 4, 4], color: "#ff8a24" },
        { pos: [2, 4, 4], color: "#ff8a24" },
        { pos: [2, 3, 5], color: "#ff8a24" },
        { pos: [2, 4, 5], color: "#ff8a24" },
        { pos: [3, 4, 5], color: "#ff8a24" },
        { pos: [3, 4, 4], color: "#ff8a24" },
        { pos: [5, 4, 5], color: "#4bb763" },
        { pos: [6, 4, 5], color: "#4bb763" },
        { pos: [6, 3, 5], color: "#4bb763" },
        { pos: [6, 4, 4], color: "#4bb763" },
        { pos: [7, 4, 4], color: "#4bb763" },
      ],
      missing: [5, 4, 4],
      candidates: [
        { label: "A", anchor: [6, 4, 5], face: "+y" },
        { label: "B", anchor: [5, 4, 5], face: "-z" },
        { label: "C", anchor: [6, 3, 5], face: "-x" },
        { label: "D", anchor: [6, 3, 5], face: "-z" },
      ],
    },
    example2: {
      voxels: [
        { pos: [2, 3, 4], color: "#ff8a24" },
        { pos: [2, 4, 4], color: "#ff8a24" },
        { pos: [2, 5, 4], color: "#ff8a24" },
        { pos: [3, 5, 4], color: "#ff8a24" },
        { pos: [3, 4, 4], color: "#ff8a24" },
        { pos: [3, 4, 5], color: "#ff8a24" },
        { pos: [4, 4, 5], color: "#ff8a24" },
        { pos: [5, 4, 5], color: "#4bb763" },
        { pos: [6, 4, 4], color: "#4bb763" },
        { pos: [6, 5, 4], color: "#4bb763" },
        { pos: [7, 5, 4], color: "#4bb763" },
        { pos: [7, 4, 4], color: "#4bb763" },
        { pos: [7, 3, 4], color: "#4bb763" },
      ],
      missing: [6, 4, 5],
      candidates: [
        { label: "A", anchor: [6, 4, 4], face: "+z" },
        { label: "B", anchor: [6, 5, 4], face: "+z" },
        { label: "C", anchor: [5, 4, 5], face: "+y" },
        { label: "D", anchor: [7, 3, 4], face: "+z" },
      ],
    },
    test: {
      voxels: [
        { pos: [2, 4, 4], color: "#ff8a24" },
        { pos: [2, 4, 3], color: "#ff8a24" },
        { pos: [2, 3, 3], color: "#ff8a24" },
        { pos: [2, 3, 4], color: "#ff8a24" },
        { pos: [3, 3, 3], color: "#ff8a24" },
        { pos: [3, 4, 3], color: "#ff8a24" },
        { pos: [3, 5, 3], color: "#ff8a24" },
        { pos: [4, 4, 3], color: "#ff8a24" },
        { pos: [5, 4, 3], color: "#4bb763" },
        { pos: [6, 5, 3], color: "#4bb763" },
        { pos: [6, 4, 3], color: "#4bb763" },
        { pos: [6, 3, 3], color: "#4bb763" },
        { pos: [7, 3, 3], color: "#4bb763" },
        { pos: [7, 4, 3], color: "#4bb763" },
        { pos: [7, 4, 4], color: "#4bb763" },
      ],
      missing: [7, 3, 4],
      candidates: [
        { label: "A", anchor: [6, 4, 3], face: "+z" },
        { label: "B", anchor: [7, 4, 3], face: "+y" },
        { label: "C", anchor: [7, 4, 4], face: "+x" },
        { label: "D", anchor: [7, 3, 3], face: "+z" },
      ],
    },
  },
};
